Invitation = ['Rehan,' 'Daud' , 'Younus']
print(Invitation[0] + "I would like to invite you to dinner ")
print(Invitation[1] + "I would like to invite you to dinner ")
print(Invitation[2] + "I would like to invite you to dinner ")
print(Invitation[0] + "can not make it")
Invitation.pop(0)
Invitation.append('Iqra')
print(Invitation)
print(Invitation[0] + "I would like to invite you to dinner ")
print(Invitation[1] + "I would like to invite you to dinner ")
print(Invitation[2] + "I would like to invite you to dinner ")